# -*- coding: utf-8 -*-
"""disaster.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13Hp_2-ksXCR2e3QFwjCwWPrP2hvGuU7i
"""

# Basic imports
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# NLP
import re
import string
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

# Forecasting
from prophet import Prophet

# System
import warnings
warnings.filterwarnings("ignore")

import pandas as pd

# Load your dataset
df = pd.read_csv("crisis.csv")

# Check basic info
print(df.shape)
print(df.columns)
print(df['crisis_type'].value_counts())



import re

def clean_text(t):
    t = str(t).lower()
    t = re.sub(r"http\S+", "", t)      # remove urls
    t = re.sub(r"@\w+", "", t)         # remove mentions
    t = re.sub(r"#", "", t)            # remove hashtags symbol
    t = re.sub(r"[^a-zA-Z\s]", "", t)  # keep only letters
    t = re.sub(r"\s+", " ", t).strip()
    return t

df['text_clean'] = df['text'].apply(clean_text)
df[['text', 'text_clean']].head()

df.info()
print(df.isnull().sum())

df.head()

# Drop the original text column
df = df.drop('text', axis=1)

# Rename text_clean to text
df = df.rename(columns={'text_clean': 'text'})

# Check result
print(df.columns)
df.head()

# Reorder columns: make text the 4th column
cols = list(df.columns)
# Remove 'text' from list and insert at index 3 (0-based)
cols.insert(3, 'text')
df = df[cols]

# Check result
print(df.columns)

df.head()

# Drop the last column (duplicate 'text')
df = df.loc[:, ~df.columns.duplicated()]

# Verify the columns
print(df.columns)

print(df.info())
print(df.isnull().sum())

df['text'].head()

import matplotlib.pyplot as plt

df['crisis_type'].value_counts().plot(kind='bar', color='skyblue')
plt.title("Crisis Type Distribution")
plt.xlabel("Crisis Type")
plt.ylabel("Count")
plt.show()

df['location'].value_counts().head(10).plot(kind='barh', color='green')
plt.title("Top 10 Locations Mentioned")
plt.xlabel("Tweet count")
plt.ylabel("Location")
plt.show()

# ============================================
# STEP 5: Split Data
# ============================================
X = df['text']
y = df[['crisis_type','location']]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# ============================================
# STEP 6: Feature Engineering (TF-IDF)
# ============================================
vectorizer = TfidfVectorizer(max_features=5000, stop_words='english')
X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)

from sklearn.multioutput import MultiOutputClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score, classification_report

# ============================================
# STEP 6: Train Multiple Multi-Output Models
# ============================================

models = {
    "Logistic Regression": MultiOutputClassifier(LogisticRegression(max_iter=1000)),
    "Naive Bayes": MultiOutputClassifier(MultinomialNB()),
    "SVM": MultiOutputClassifier(LinearSVC()),
    "Random Forest": RandomForestClassifier(n_estimators=200, random_state=42)  # RF supports multi-output natively
}

results = {}

for name, model in models.items():
    model.fit(X_train_tfidf, y_train)  # y_train has 2 columns
    y_pred = model.predict(X_test_tfidf)

    # Calculate accuracy for each label separately
    acc_crisis = accuracy_score(y_test['crisis_type'], y_pred[:, 0])
    acc_location = accuracy_score(y_test['location'], y_pred[:, 1])

    # Store combined report
    results[name] = (acc_crisis, acc_location)

    print(f"\n==== {name} ====")
    print(f"Crisis Type Accuracy : {acc_crisis:.4f}")
    print(f"Location Accuracy    : {acc_location:.4f}")
    print("\nCrisis Type Report:")
    print(classification_report(y_test['crisis_type'], y_pred[:, 0]))
    print("\nLocation Report:")
    print(classification_report(y_test['location'], y_pred[:, 1]))

# ============================================
# STEP 7: Compare Model Accuracies
# ============================================
import numpy as np

model_names = list(results.keys())
crisis_acc = [results[m][0] for m in model_names]
location_acc = [results[m][1] for m in model_names]

x = np.arange(len(model_names))
width = 0.35

plt.figure(figsize=(9,5))
plt.bar(x - width/2, crisis_acc, width, label="Crisis Type Accuracy")
plt.bar(x + width/2, location_acc, width, label="Location Accuracy")

plt.xticks(x, model_names, rotation=15)
plt.ylabel("Accuracy")
plt.title("Model Accuracy Comparison (Multi-Output)")
plt.legend()
plt.show()

!python -m spacy download en_core_web_sm

import spacy
nlp = spacy.load("en_core_web_sm")

def extract_location(text):
    doc = nlp(text)
    for ent in doc.ents:
        if ent.label_ in ["GPE", "LOC"]:  # GPE = Countries, Cities, States
            return ent.text
    return None

def predict_crisis(text):
    # Convert text to TF-IDF
    text_tfidf = vectorizer.transform([text])

    # Best model
    best_model = models["Random Forest"]

    # Predict crisis + location (model output)
    pred = best_model.predict(text_tfidf)[0]
    crisis_pred = pred[0]

    # Extract location using NER
    ner_location = extract_location(text)

    # Final location logic
    if ner_location:
        final_location = ner_location   # use NER-detected location
    else:
        final_location = "Unknown"      # instead of model predicted wrong place

    # The function must return values for Gradio to unpack
    return crisis_pred, final_location

predict_crisis("Huge fire near the marketplace, people are being evacuated!")
predict_crisis("Flood alerts issued in Mumbai, stay indoors and safe!")
predict_crisis("Explosion reported at refinery plant, rescue teams deployed.")
predict_crisis("Vaccination centers in Nevada are overwhelmed with long queues.")

import gradio as gr

def gradio_predict_crisis(text):
    # The predict_crisis function must return the values to be unpacked here
    crisis_pred, final_location = predict_crisis(text)
    return f"Predicted Crisis Type: {crisis_pred}", f"Predicted Location: {final_location}"


iface = gr.Interface(fn=gradio_predict_crisis,
                     inputs=gr.Textbox(lines=5, label="Enter text for crisis prediction"),
                     outputs=[gr.Textbox(label="Crisis Type"), gr.Textbox(label="Location")],
                     title="Crisis Type and Location Predictor",
                     description="Enter a tweet or text to predict the crisis type and location.")

iface.launch(debug=True)

import joblib

# Save the best model (Random Forest) and the TF-IDF vectorizer
best_model_name = "Random Forest"
best_model = models[best_model_name]

joblib.dump(best_model, 'random_forest_model.joblib')
joblib.dump(vectorizer, 'tfidf_vectorizer.joblib')

print(f"'{best_model_name}' model and TF-IDF vectorizer saved successfully.")